"""Updated Schema of User Table

Revision ID: 26b47c19af35
Revises: 1f62697ed377
Create Date: 2026-03-07 08:09:31.417839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b47c19af35'
down_revision: Union[str, None] = '1f62697ed377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider_id', sa.String(length=255), nullable=True))
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['provider_id'])
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.drop_column('users', 'provider_id')
    # ### end Alembic commands ###
