"""Created CodeReview Database Table

Revision ID: 31746c4f10fe
Revises: b2ff04c29fdf
Create Date: 2026-02-24 19:03:33.205221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31746c4f10fe'
down_revision: Union[str, None] = 'b2ff04c29fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('technology_stack_understanding', sa.Text(), nullable=False),
    sa.Column('architecture_review', sa.Text(), nullable=False),
    sa.Column('security_assessment', sa.Text(), nullable=False),
    sa.Column('authentication_quality', sa.Text(), nullable=False),
    sa.Column('database_design_review', sa.Text(), nullable=False),
    sa.Column('async_concurrency_risks', sa.Text(), nullable=False),
    sa.Column('performance_risks', sa.Text(), nullable=False),
    sa.Column('production_readiness_score', sa.Integer(), nullable=False),
    sa.Column('technical_debt_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='technical_debt_enum'), nullable=False),
    sa.Column('risk_severity_distribution', sa.JSON(), nullable=False),
    sa.Column('top_prioritized_improvements', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_reviews_id'), 'code_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_code_reviews_user_id'), 'code_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_reviews_user_id'), table_name='code_reviews')
    op.drop_index(op.f('ix_code_reviews_id'), table_name='code_reviews')
    op.drop_table('code_reviews')
    # ### end Alembic commands ###
